### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by mikebutts** [LucyClaxton/prj-rev-bwfs-dasmoto#3]
Meets Expectations

Very well done this looks close to spec. Good job on this project, I left a couple issue open to help your code semantically but will not change the look of your code. Adding divs just helping reading it later and quickly spot the groups of code. Next, try to spice up the page, maybe add a background image for the header or some colors to the divs. Coolors.co has some cool schemes you can check out. Another idea is centering the image and text so it's not all left aligned.

**Comment by LucyClaxton** [comment]
Thank you for the feedback. I just did what it looked like on the example on Codecademy. However, I will have a play around and "spice things up a bit" ;-)
